import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { beforeAll, describe, expect, it } from 'vitest';

import { MOBILE_WEB_DIR } from '../../webDir';
import { injectNativePermissions } from '../../scripts/injectPermissions.mjs';

/**
 * Capacitor wrapper build + native-scaffolding validation for the mobile app.
 *
 * Android SDK/Gradle and Xcode are unavailable in this workspace, so the native
 * artifact build (`cap add android/ios`, Gradle/xcodebuild) cannot run here. The
 * things this suite CAN prove without that toolchain are exactly the failure
 * modes that ship a broken Capacitor wrapper:
 *
 *   1. The production WebView bundle actually emits — and lands in the SAME
 *      directory Capacitor declares as `webDir` (a drift here makes `cap sync`
 *      ship an empty or stale shell).
 *   2. `capacitor.config.ts` is a parseable CapacitorConfig with the immutable
 *      `appId` and the shared `webDir` (a wrong appId breaks signing/upgrades
 *      irreversibly; a wrong webDir ships nothing).
 *   3. The re-runnable permission-injection mechanism injects every native
 *      permission the wallet's plugins need (camera for barcode scanning,
 *      biometric, and the iOS usage-description strings) — because the native
 *      projects are regenerated by `cap add` and must NOT be hand-edited.
 */
const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP_ROOT = path.resolve(HERE, '..', '..');
const REPO_ROOT = path.resolve(APP_ROOT, '..', '..');
const WEB_DIR = path.join(APP_ROOT, MOBILE_WEB_DIR);

function webDirPath(rel: string): string {
  return path.join(WEB_DIR, rel.replace(/^\/+/, ''));
}

describe('mobile Capacitor WebView build emits into the shared webDir', () => {
  beforeAll(() => {
    rmSync(WEB_DIR, { recursive: true, force: true });
    // Build through the workspace filter so the real shipped pipeline runs.
    execFileSync('pnpm', ['--filter', '@stoawallet/mobile', 'build:web'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      timeout: 300_000,
      stdio: 'pipe',
      shell: process.platform === 'win32',
    });
  }, 320_000);

  it('emits a non-empty index.html into the directory Capacitor declares as webDir', () => {
    const indexHtml = webDirPath('index.html');
    expect(existsSync(indexHtml)).toBe(true);
    const html = readFileSync(indexHtml, 'utf8');
    expect(html.trim().length).toBeGreaterThan(0);
    // The bundle must reference its hashed JS asset, proving Vite actually
    // wired the entry — not just copied a bare template.
    expect(html).toMatch(/<script[^>]+src=/i);
  });

  it('emits the hashed JS bundle the index.html references', () => {
    const indexHtml = readFileSync(webDirPath('index.html'), 'utf8');
    const srcMatch = indexHtml.match(/<script[^>]+src="([^"]+)"/i);
    expect(srcMatch).not.toBeNull();
    const assetRel = srcMatch![1].replace(/^\/+/, '');
    expect(existsSync(webDirPath(assetRel))).toBe(true);
  });
});

describe('capacitor.config declares the immutable identity and shared webDir', () => {
  let config: { appId?: string; appName?: string; webDir?: string };

  beforeAll(async () => {
    const mod = await import('../../capacitor.config');
    config = (mod.default ?? mod) as typeof config;
  });

  it('pins the immutable appId so native signing and store-upgrade identity never break', () => {
    // appId is the irreversible Android applicationId / iOS bundle identifier.
    expect(config.appId).toBe('com.stoachain.wallet');
  });

  it('sets webDir from the SAME shared constant Vite builds into, so cap sync ships the real bundle', () => {
    expect(config.webDir).toBe(MOBILE_WEB_DIR);
  });

  it('names the app StoaWallet', () => {
    expect(config.appName).toBe('StoaWallet');
  });
});

describe('re-runnable native permission injection', () => {
  it('injects the camera permission and barcode manifest entries into Android manifest XML', () => {
    const androidManifest = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:label="@string/app_name"></application>
</manifest>`;
    const out = injectNativePermissions({ platform: 'android', source: androidManifest });
    expect(out).toContain('android.permission.CAMERA');
    // The barcode plugin needs its camera-feature declaration so the Play
    // Store filters correctly and the scanner can open the camera.
    expect(out).toContain('android.hardware.camera');
  });

  it('is idempotent on Android — re-running does not duplicate the camera permission', () => {
    const androidManifest = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application></application>
</manifest>`;
    const once = injectNativePermissions({ platform: 'android', source: androidManifest });
    const twice = injectNativePermissions({ platform: 'android', source: once });
    const occurrences = twice.split('android.permission.CAMERA').length - 1;
    expect(occurrences).toBe(1);
  });

  it('injects non-empty NSCameraUsageDescription and NSFaceIDUsageDescription into iOS Info.plist', () => {
    const infoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>StoaWallet</string>
</dict>
</plist>`;
    const out = injectNativePermissions({ platform: 'ios', source: infoPlist });
    expect(out).toContain('NSCameraUsageDescription');
    expect(out).toContain('NSFaceIDUsageDescription');
    // The usage-description copy must be a non-empty human-readable string, or
    // Apple rejects the binary at review.
    const cameraCopy = out.match(
      /<key>NSCameraUsageDescription<\/key>\s*<string>([^<]+)<\/string>/,
    );
    expect(cameraCopy).not.toBeNull();
    expect(cameraCopy![1].trim().length).toBeGreaterThan(0);
    const faceCopy = out.match(
      /<key>NSFaceIDUsageDescription<\/key>\s*<string>([^<]+)<\/string>/,
    );
    expect(faceCopy).not.toBeNull();
    expect(faceCopy![1].trim().length).toBeGreaterThan(0);
  });

  it('is idempotent on iOS — re-running does not duplicate the usage-description key', () => {
    const infoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>StoaWallet</string>
</dict>
</plist>`;
    const once = injectNativePermissions({ platform: 'ios', source: infoPlist });
    const twice = injectNativePermissions({ platform: 'ios', source: once });
    const occurrences = twice.split('NSCameraUsageDescription').length - 1;
    expect(occurrences).toBe(1);
  });
});
